server:
  port: 9201
spring:
  redis:
    host: localhost
    port: 16379
    database: 0
    password: datagrand
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: path_route #路由的ID
          uri: http://localhost:8201 #匹配后路由地址
          predicates: # 断言，路径相匹配的进行路由
            - Path=/user-service/**
          filters:
            - StripPrefix=1
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 1 #每秒允许处理的请求数量
                redis-rate-limiter.burstCapacity: 2 #每秒最大处理的请求数量
                key-resolver: "#{@ipKeyResolver}" #限流策略，对应策略的Bean
#            - name: Hystrix
#              args:
#                name: fallbackcmd
#                fallbackUri: forward:/fallback
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/
logging:
  level:
    org.springframework.cloud.gateway: debug